# 第五讲：转置，置换，向量空间R

### 置换矩阵（Permutation Matrix）

$P$为置换矩阵，对任意可逆矩阵$A$有：
$PA = LU$
$n$阶方阵的置换矩阵$P$有$\binom{n}{1}=n!$个
对置换矩阵$P$，有$P^TP$ = $I$ （下面可以证明）
即$P^T = P^{-1}$

转置矩阵（Transpos Matrix)
$$
(A^T)_{ij} = (A)_{ji}
$$
对称矩阵(Symmetrix Matrix)
$$
A^T = A
$$
对任意矩阵$R$有$R^TR$为对称矩阵：

$$
(R^TR)^T = (R)^T(R^T)^T = R^TR \\
\textrm{即}(R^TR)^T = R^TR
$$
向量空间（VectorSpace)
所有向量都必须包含原点（Origin)
向量空间中任意向量的数乘，求和运算得到的向量也在该空间中。
即向量空间要满足加法封闭和数乘封闭。


In [8]:
import numpy as np

In [9]:
a = np.array([[0,1,0],
              [0,0,1],
              [1,0,0]])
a.T

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

In [10]:
a.T.dot(a)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [11]:
b = np.array([[3,1,1],
              [4,5,1],
              [2,6,3]])
b.T

array([[3, 4, 2],
       [1, 5, 6],
       [1, 1, 3]])

In [12]:
b.T.dot(b)

array([[29, 35, 13],
       [35, 62, 24],
       [13, 24, 11]])