In [1]:
import numpy as np
import pandas as pd

In [2]:
#定义一个简单的数据，使得数据符合y = x1 + X2
df = pd.DataFrame({'x1':[1,2,3,4,5,6],'x2':[1,2,1,2,1,2],'y':[2,4,4,6,6,8]})
x = df[['x1','x2']]
y = df['y'].values.reshape([-1,1])
x
print(y)

[[2]
 [4]
 [4]
 [6]
 [6]
 [8]]


In [3]:
theta = np.array([[1],[2]])
theta

array([[1],
       [2]])

In [43]:
x.dot(theta)-y

0
0  1
1  2
2  1
3  2
4  1
5  2

In [44]:
x.T

0  1  2  3  4  5
x1  1  2  3  4  5  6
x2  1  2  1  2  1  2

In [45]:
x.T.dot(x.dot(theta)-y)

0
x1  33
x2  15

In [46]:
#BGD ：批量梯度下降------初始化theta,给定一个alpha
theta = np.array([[0],[0]])
alpha = 0.01
theta

array([[0],
       [0]])

In [47]:
#BGD 迭代
theta = theta - alpha * x.T.dot(x.dot(theta)-y)
loss = np.power(x.dot(theta)-y,2).sum()
print('loss为%f \ntheta为\n'%loss,theta.values)

loss为1.060800 
theta为
 [[ 1.24]
 [ 0.48]]


In [48]:
#$\theta_j = \theta_j$ + $\alpha\sum_{i=1}^m\left(y[i] - h($\theta)\(x_i)\right)(x_j)[i]

In [49]:
#随机梯度下降-SGD
#初始化theta,给定一个alpha
x_s = x.sample(frac=1).values
print(x_s)
theta_s = np.array([0,0])
alpha_s = 0.03

[[1 1]
 [6 2]
 [3 1]
 [4 2]
 [2 2]
 [5 1]]


In [56]:
#随机梯度下降---迭代
for i in range(6):
    theta_s = theta_s - alpha_s * (x_s[i].dot(theta_s) - y[i])*x_s[i].T
    loss = np.power(x_s.dot(theta_s)-y,2).sum()
    print('loss值为%f \n theta值为\n'%loss,theta_s)

loss值为392.913949 
 theta值为
 [ 1.40690529  0.67715906]
loss值为525.309917 
 theta值为
 [ 0.36367032  0.32941407]
loss值为366.295966 
 theta值为
 [ 0.59583207  0.40680131]
loss值为263.419439 
 theta值为
 [ 0.93220036  0.57498546]
loss值为281.902126 
 theta值为
 [ 1.11133806  0.75412316]
loss值为387.992606 
 theta值为
 [ 1.36471604  0.80479876]


In [51]:
x[1:1+2]
y[1:1+2]

array([[4],
       [4]], dtype=int64)

In [54]:

#小批量MBGD
theta_m = np.array([[0],[0]])
alpha_m = 0.03
flag = True
for i in range(3):
    theta_m = theta_m - alpha * x[i:i+2].T.dot(x[i:i+2].dot(theta_m) -y[i:i+2])
    loss = np.power(x.dot(theta_m)-y,2).sum()
    print('loss值为%f \n theta值为\n'%loss,theta_m.values)

loss值为139.320000 
 theta值为
 [[ 0.1]
 [ 0.1]]
loss值为94.219200 
 theta值为
 [[ 0.28 ]
 [ 0.208]]
loss值为45.584102 
 theta值为
 [[ 0.54712]
 [ 0.3268 ]]
